### Why Numpy 
###### In python we can use list but list is the scattered address of pointers which points every element in the list
###### It takes almost 28 bytes of space in the device
###### There is no vectorization in list if we are given 1000000 elements we need a loop
###### There can be different data type of each element which makes it time consuming
###### we need to write loops every time to preform mathematical operation 


#### Numpy is a continues block of memory allocation of same data type, a single interger in numpy takes 8 bytes of sapce in the deviuce
#### very easy to perform mathematically operations without loop
#### supports vectorization in array

In [2]:
import numpy as np
#arhgang


In [2]:
matrix = [
    [1,2,3],
    [2,3,4],
    [3,4,5]
]
new_matrix = np.array(matrix)
new_matrix

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

### syntax of numpy

###### np.arange(start, stop, step)
###### np.zeros(m,n) ## genrally used to start the cost function of ML model
###### np.ones(m,n)
###### np.linespace(start, stop, division)    ##(1,10,2) ## (1,10)
###### np.eye(n) ###IT create an identity matrix of size n in float64 OR np.identity(n)


In [3]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((1,2))

array([[1., 1.]])

In [9]:
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Random Number in Numpy 

##### Functions 
##### np.random.rand(n) generated n number from the range(0-1) in float dtype
##### np.random.randn(n) generates the number for +ve and -ve with the extreme range present in the normal distribution form
##### np.random.randint(start range, stop range) It generates the number present in the given bound
##### np.empty((m,n)) generates any random number to form M x N matrix


In [12]:
np.random.rand(3)

array([0.94405554, 0.68483344, 0.38857023])

In [28]:
np.random.randn(5)

array([-0.50696513, -0.25350589, -0.69593756, -1.34496037,  0.26546006])

In [3]:
np.random.randint(2,10,5)

array([2, 4, 9, 9, 7], dtype=int32)

In [32]:
np.empty((2,3))

array([[6.23042070e-307, 1.33512376e-306, 1.11261230e-306],
       [7.56577399e-307, 9.34600963e-307, 1.20741561e-311]])

### Rehape an array

In [33]:
matrix = np.array([
    [1,2,3,4,5],
    [2,3,4,5,6]
])
new = matrix.reshape(5,2)

In [34]:
new

array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]])

In [35]:
horizontal = new.ravel()
horizontal

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6])

In [43]:
short_array = np.array([12,34,12,34,21,56,45,34])
short_array.sort()
short_array
short_array.nbytes
short_array.ndim

1

### Slicing in array
###### variable[ start : stop : slice]

In [38]:
new_array = np.array([12,34,56,44,23,78,23,45,67])
new_array[:]

array([12, 34, 56, 44, 23, 78, 23, 45, 67])

In [39]:
new_array[1:]

array([34, 56, 44, 23, 78, 23, 45, 67])

In [40]:
new_array[2::4]

array([56, 23])

### Condition in array
##### new_array > 10 returns BOOLEAN value if greater than 10


In [41]:
new_array > 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

### Operation in array
###### Addind an array [array1] + [array2] (works in indexing)
###### substrating an array [array1] - [array2] (works in indexing)
###### multiplication in array [array1] * number (multiplies every element with that number and return the new array)
###### division in array [array1] / number (divides every element with the given number)
###### square root in an array np.sqrt(array1) (gives the list or matrix form of array with the square root of each element in it)
###### total sum of array np.sum(array1) 
###### standard deviation in an array np.std(array1)
###### Transpose of a matix array1.T

### Advance numpy

In [45]:
## Stacking vertical

a = np.array([1,2,3])
b = np.array([2,3,4])
c = np.vstack((a,b))
c

array([[1, 2, 3],
       [2, 3, 4]])

In [46]:
## Stacking horizontal
a = np.array([1,2,3])
b = np.array([2,3,4])
c = np.hstack((a,b))
c

array([1, 2, 3, 2, 3, 4])

In [48]:
## Splitting in matrix
matrix = np.array([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6],
    [4,5,6,7]
])
new_vmatix1, new_vmatix2 = np.vsplit(matrix, 2) 
print("Matrix 1:\n", new_vmatix1)
print("Matrix 2:\n", new_vmatix2)

Matrix 1:
 [[1 2 3 4]
 [2 3 4 5]]
Matrix 2:
 [[3 4 5 6]
 [4 5 6 7]]


In [49]:
matrix = np.array([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6],
    [4,5,6,7]
])
new_vmatix1, new_vmatix2 = np.hsplit(matrix, 2) 
print("Matrix 1:\n", new_vmatix1)
print("Matrix 2:\n", new_vmatix2)

Matrix 1:
 [[1 2]
 [2 3]
 [3 4]
 [4 5]]
Matrix 2:
 [[3 4]
 [4 5]
 [5 6]
 [6 7]]


In [51]:
## Linear Algebra using NumPy
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = A @ B
print(A.T)
result

[[1 3]
 [2 4]]


array([[19, 22],
       [43, 50]])

In [52]:
## solving a algebric equation
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 11])
x = np.linalg.solve(A, B)
x

array([1., 2.])