### K-Fold Cross Validation

##### Best for Classification problrm

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import KFold

digits = load_digits()

In [9]:
kf = KFold(n_splits= 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size=0.3 )

In [16]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [17]:
get_score(LogisticRegression(),X_train, X_test, y_train, y_test)

C:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9722222222222222

In [18]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [23]:
score_log = []
score_svm = []
score_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    log_res = get_score(LogisticRegression(), X_train, X_test, y_train, y_test)
    svm_res = get_score(SVC(), X_train, X_test, y_train, y_test)
    rf_res  = get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

    score_log.append(log_res)
    score_svm.append(svm_res)
    score_rf.append(rf_res)






C:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_resu

In [24]:
score_log

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [25]:
score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [26]:
score_rf

[0.9315525876460768, 0.9649415692821369, 0.9282136894824707]

In [27]:
from sklearn.model_selection import cross_val_score

In [29]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [40]:
cross_val_score(RandomForestClassifier(n_estimators = 10), digits.data, digits.target, cv = folds)

array([0.88313856, 0.90984975, 0.89482471])

In [ ]:
cross_val_score(LogisticRegression(n_estimators = 10), digits.data, digits.target)

array([0.93489149, 0.95325543, 0.92487479])

In [41]:
cross_val_score(RandomForestClassifier(n_estimators = 100), digits.data, digits.target, cv = folds)

array([0.93322204, 0.95659432, 0.92654424])

## Leave one out cross validation

##### Works on small dataset trains on row -1 data and test on that single row


In [42]:
from sklearn.model_selection import LeaveOneOut, cross_val_score
loo = LeaveOneOut()
model = RandomForestClassifier(n_estimators=50, random_state=42)

In [43]:
X_subset = digits.data[:100]
y_subset = digits.target[:100]

In [44]:
scores = cross_val_score(model, X_subset, y_subset, cv=loo)

In [45]:
print(f"Total iterations run: {len(scores)}")
print(f"LOOCV Accuracy: {scores.mean() * 100:.2f}%")

Total iterations run: 100
LOOCV Accuracy: 92.00%


## Leave P out cross validation

##### It works same as above but works on N-P data points

## Repeated K fold 

##### Sometimes, just doing 5-fold cross-validation once isn't enough because the initial random split can still introduce a bit of luck (good or bad).

#####  It repeats the entire K-Fold process $N$ times, shuffling the data differently each time. If you do a 5-Fold split repeated 3 times, you get a total of 15 separate evaluations.